name: mobile
description: A customer service ticketing mobile application built with Flutter, Stripe & Firebase
publish_to: "none"

version: 1.0.7+1

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.10.4 <4.0.0"

dependency_overrides:
  http: ^0.13.3
  google_fonts: ^5.1.0
  intl: ^0.18.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  device_preview: ^1.1.0
  shared_preferences: ^2.1.2
  heroicons: ^0.9.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  flutter_animate: ^4.2.0
  pinput: ^3.0.0
  api_utils:
    git:
      url: git://github.com/quabynah-bilson/api_utils.git
  dio: ^5.3.2
  retrofit: ^4.0.1
  shared_utils:
    git:
      url: git://github.com/quabynah-bilson/shared_utils.git
  easy_localization: ^3.0.2
  get_it: ^7.6.0
  envied: ^0.3.0+3
  injectable: ^2.1.2
  intl: ^0.18.1
  lottie: ^2.4.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.4
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1
  crypto: ^3.0.3
  cloud_firestore: ^4.8.4
  hive_flutter: ^1.1.0
  copy_with_extension: ^5.0.3
  intercom_flutter: ^8.0.0
  animated_bottom_navigation_bar: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.5
  change_app_package_name: ^1.1.0
  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  mocktail: ^1.0.0
  flutter_native_splash:
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/anim/
    - assets/brand/
    - assets/img/
    - assets/translations/
    - assets/data/

# dart run flutter_launcher_icons
# make background transparent for android
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/app_logo_white.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/app_logo_white.png"
  adaptive_icon_mask: true
  web:
    generate: true
    image_path: "assets/img/app_logo_white.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/img/app_logo_white.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img/app_logo_white.png"

# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/img/app_logo_white.png
  image_dark: assets/img/app_logo_white.png
  icon_background_color: "#ffffff"
  color: "#ffffff"
  color_dark: "#ffffff"
  icon_background_color_dark: "#ffffff"
  web: false
  web_image_mode: contain
  android_12:
    image: assets/img/app_logo_white.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#ffffff"
    color_dark: "#ffffff"
    image_dark: assets/img/app_logo_white.png
