// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTywerBbNJGjX1xnF58_MbHhhdTfTX_lc',
    appId: '1:479771909152:web:890150b2dd4617c4dbf045',
    messagingSenderId: '479771909152',
    projectId: 'swiftly-team',
    authDomain: 'swiftly-team.firebaseapp.com',
    storageBucket: 'swiftly-team.appspot.com',
    measurementId: 'G-6Y0FY24JMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4E2rgFjmsBY1J50m4hLuh8dds60H44nA',
    appId: '1:479771909152:android:69671d79ae01b1b3dbf045',
    messagingSenderId: '479771909152',
    projectId: 'swiftly-team',
    storageBucket: 'swiftly-team.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC42zXoVyNpJ7KlPdj1JkjqRWnQWvmgMmk',
    appId: '1:479771909152:ios:43a476c1b4c4d929dbf045',
    messagingSenderId: '479771909152',
    projectId: 'swiftly-team',
    storageBucket: 'swiftly-team.appspot.com',
    iosClientId: '479771909152-n0gssmfktgqc771f49sd1nq5arjm2sc7.apps.googleusercontent.com',
    iosBundleId: 'com.swiftly.ios',
  );
}
