// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcvoFN1aEjWsgIZISlEFHYAuRIrs-8_YY',
    appId: '1:530372023150:android:4c3b243dfbdf75a6c4677f',
    messagingSenderId: '530372023150',
    projectId: 'swiftly-by-qcodelabsllc',
    storageBucket: 'swiftly-by-qcodelabsllc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP0UjKfVkbHf-JlFKpYaVRdpXXM3Xug8g',
    appId: '1:530372023150:ios:72cc8e5cb512c22fc4677f',
    messagingSenderId: '530372023150',
    projectId: 'swiftly-by-qcodelabsllc',
    storageBucket: 'swiftly-by-qcodelabsllc.appspot.com',
    androidClientId: '530372023150-h9c64nhe3ltchpm7vrd33ckljmok8mu8.apps.googleusercontent.com',
    iosClientId: '530372023150-mrpfp0k6re3hhnsv23ohk4prok4srvpj.apps.googleusercontent.com',
    iosBundleId: 'io.qcodelabsllc.swiftly.mobile',
  );
}
